name: Simple Workflow

on:
    workflow_dispatch:
      inputs:
        text:
          description: 'Input text to generate artifact'
          required: false
          default: 'null'

jobs:

    TIMESTAMP:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: 1.0 GET TIMESTAMP
          id: time
          uses: nanzm/get-time-action@v1.1
          with:
            timeZone: 3
            format: 'YYYY-MM-DD HH:mm:ss'
        - name: 1.1 UPLOADING FILES
          run: |
            cp ./scripts/main.py ./.github/actions/action_1.2/main.py
        - name: 1.2 EXECUTING THE PYTHON SCRIPT
          uses: ./.github/actions/action_1.2
        - name: 1.3 CREATE OUTPUT FILE
          uses: "finnp/create-file-action@master"
          env:
            FILE_NAME: "/home/runner/work/devops-school/devops-school/output.txt"
            FILE_DATA: ${{ steps.time.outputs.time }} ${{  github.event.inputs.text  }}
        - name: 1.4.1 DOWNLOAD ARTIFACT
          uses: actions/upload-artifact@v2
          with:
              name: log.md
              path: /home/runner/work/devops-school/devops-school/log.md
        - name: 1.4.2 DOWNLOAD ARTIFACT
          uses: actions/upload-artifact@v2
          with:
              name: output.txt
              path: /home/runner/work/devops-school/devops-school/output.txt
